# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Local Gov_Base
# label used for menu selection
label: Local_Gov
description: This is a base configuration for local government customers

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - LocalGov

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: INCLUDE_COUNTRY_BLOCK
    description: Add rules to permit traffic only from US, Mexico, Canada, and Cloud Providers EDL
    default: 'no'
    type_hint: dropdown
    dd_list:
     - key: 'yes'
       value: 'yes'
     - key: 'no'
       value: 'no'
  - name: Untrust_zone_interface
    description: Untrust interface
    default: ethernet1/1
    type_hint: text
  - name: Trust_zone_interface
    description: Trust Interface
    default: ethernet1/2
    type_hint: text
  - name: TRUSTED_INTERFACE_IP
    description: Trusted Interface IP
    default: 10.10.1.1/32
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: color-580736
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag/entry[@name="Outbound"]
    element: |-
        <color>color20</color>

  - name: color-974093
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag/entry[@name="Inbound"]
    element: |-
        <color>color21</color>

  - name: color-955686
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag/entry[@name="Internal"]
    element: |-
        <color>color4</color>

  - name: entry-84143
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag
    element: |-
        <entry name="NIST">
                      <color>color10</color>
                      <comments>NIST- Compliance rules </comments>
                    </entry>

  - name: entry-873654
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag
    element: |-
        <entry name="CJIS">
                      <color>color24</color>
                      <comments>CJIS Compliance rules </comments>
                    </entry>

  - name: entry-602579
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag
    element: |-
        <entry name="Deny">
                      <color>color1</color>
                      <comments>Blocked traffic</comments>
                    </entry>

  - name: entry-351099
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="ethernet1/1">
                      <layer3>
                        <ipv6>
                          <neighbor-discovery>
                            <router-advertisement>
                              <enable>no</enable>
                            </router-advertisement>
                          </neighbor-discovery>
                        </ipv6>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                        <dhcp-client/>
                      </layer3>
                    </entry>

  - name: entry-412609
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="ethernet1/2">
                      <layer3>
                        <ipv6>
                          <neighbor-discovery>
                            <router-advertisement>
                              <enable>no</enable>
                            </router-advertisement>
                          </neighbor-discovery>
                        </ipv6>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                        <ip>
                          <entry name=" {{ TRUSTED_INTERFACE_IP }} "/>
                        </ip>
                      </layer3>
                    </entry>

  - name: entry-821461
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/zone
    element: |-
        <entry name="Untrust">
                      <network>
                        <layer3>
                          <member>{{ Untrust_zone_interface }}</member>
                        </layer3>
                        <zone-protection-profile>Recommended_Zone_Protection</zone-protection-profile>
                        <log-setting>default</log-setting>
                      </network>
                    </entry>

  - name: entry-237688
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/zone
    element: |-
        <entry name="Trust">
                      <network>
                        <layer3>
                          <member>{{ Trust_zone_interface }}</member>
                        </layer3>
                        <zone-protection-profile>Recommended_Zone_Protection</zone-protection-profile>
                        <log-setting>default</log-setting>
                      </network>
                    </entry>

  - name: entry-534268
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/address
    element: |-
        <entry name="Trust_IP">
                      <ip-netmask>{{ TRUSTED_INTERFACE_IP.split('/')[0] }}/32</ip-netmask>
                    </entry>

  - name: interface-80427
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]
    element: |-
        <interface>
                      <member>ethernet1/1</member>
                      <member>ethernet1/2</member>
                    </interface>

  - name: import-471795
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <import>
                    <network>
                      <interface>
                        <member>ethernet1/1</member>
                        <member>ethernet1/2</member>
                      </interface>
                    </network>
                  </import>

  - name: member-849303
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules/entry[@name="Outbound Block Rule"]/tag
    element: |-
        <member>Deny</member>

  - name: entry-681593
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
       {%- if INCLUDE_COUNTRY_BLOCK == 'yes' %}
       <entry name="Outbound Country Block" uuid="a6a493fd-fa80-4ca8-b4c2-cb08fad80bf3">
                          <profile-setting>
                            <group>
                              <member>default</member>
                            </group>
                          </profile-setting>
                          <to>
                            <member>Trust</member>
                          </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>CA</member>
                            <member>MX</member>
                            <member>US</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <tag>
                            <member>Outbound</member>
                            <member>Deny</member>
                          </tag>
                          <action>deny</action>
                          <negate-destination>yes</negate-destination>
                          <log-setting>default</log-setting>
                        </entry>

  - name: entry-668399
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-

        <entry name="Inbound Country Block" uuid="72e10e52-0bbb-4f94-82a4-bfa22092c397">
                          <profile-setting>
                            <group>
                              <member>default</member>
                            </group>
                          </profile-setting>
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>Untrust</member>
                          </from>
                          <source>
                            <member>CA</member>
                            <member>MX</member>
                            <member>US</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>deny</action>
                          <log-setting>default</log-setting>
                          <tag>
                            <member>Inbound</member>
                            <member>Deny</member>
                          </tag>
                          <negate-source>yes</negate-source>
                        </entry>
                          {% endif %}

  - name: member-442107
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules/entry[@name="Inbound Block Rule"]/tag
    element: |-
        <member>Deny</member>

  - name: member-346633
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules/entry[@name="DNS Sinkhole Block"]/tag
    element: |-
        <member>Deny</member>

  - name: entry-462566
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="Block Quic" uuid="037e9b55-a051-439d-aec0-f91f8ccc4099">
                          <profile-setting>
                            <group>
                              <member>default</member>
                            </group>
                          </profile-setting>
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>quic</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <tag>
                            <member>Deny</member>
                          </tag>
                          <action>deny</action>
                          <log-setting>default</log-setting>
                          <description>Blocking Quic will force web browsers to use SSL </description>
                        </entry>

  - name: entry-161734
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="Outbound DNS" uuid="81459213-fa0f-4fb2-9c63-a3eb4e533804">
                          <profile-setting>
                            <group>
                              <member>default</member>
                            </group>
                          </profile-setting>
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>Trust</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>dns</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>allow</action>
                          <log-setting>default</log-setting>
                          <tag>
                            <member>Outbound</member>
                          </tag>
                        </entry>

  - name: entry-274750
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="Outbound Web browsing" uuid="89c0df82-6527-4fb1-8626-3904cf344fe0">
                          <profile-setting>
                            <group>
                              <member>default</member>
                            </group>
                          </profile-setting>
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>Trust</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>google-base</member>
                            <member>ssl</member>
                            <member>web-browsing</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>allow</action>
                          <log-setting>default</log-setting>
                          <tag>
                            <member>Outbound</member>
                          </tag>
                        </entry>

  - name: entry-64247
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/decryption/rules
    element: |-
        <entry name="Decryption rule" uuid="8de3e20c-0747-40b0-89d1-c630ccf31bfc">
                          <category>
                            <member>any</member>
                          </category>
                          <service>
                            <member>any</member>
                          </service>
                          <type>
                            <ssl-forward-proxy/>
                          </type>
                          <from>
                            <member>any</member>
                          </from>
                          <to>
                            <member>Untrust</member>
                          </to>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <action>decrypt</action>
                          <profile>Recommended_Decryption_Profile</profile>
                          <disabled>yes</disabled>
                        </entry>


# ---------------------------------------------------------------------
# end of snippets section